name: Maven Package

on:
  push:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/workflows/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Get Maven Artifact Version
        id: get_version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "deployment/target/*.jar,runtime/target/*.jar"
          token: ${{ secrets.GH_TOKEN }}
          tag: v${{ steps.get_version.outputs.version }}
          commit: ${{ github.sha }}